language: node_js
node_js:
  - "node"
  - "12"
cache:
  directories:
    - node_modules
before_install:
  - npm update
  - npm install codecov -g
install:
  - npm install
after_success:
  - codecov
script:
  - npm run test